name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Forzar permisos de ejecución a gradlew
        run: chmod +x gradlew

      - name: Verificar permisos de gradlew
        run: ls -l gradlew

      - name: Ejecutar tests y generar reporte de cobertura
        run: ./gradlew testDebugUnitTest jacocoTestReport

      - name: Verificar que el reporte de Jacoco existe
        run: ls -la build/reports/jacoco/testDebugUnitTest

      - name: Ejecutar SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/testDebugUnitTest/testDebugUnitTest.xml
